### ISSUE TITLE
Default block gasLimit too large 

### ISSUE THREAD

**Issue by okwme** [cosmos/ethermint#149]
__System info:__ 021c9f440a7c3355f4fbae44a143de30ea3473d6

__Steps to reproduce:__

1. Clone https://github.com/clovers-network/clovers-contracts and install dependencies.
2. Deploy contracts to a running ethermint node with `npx buidler --network ethermint deploy --v`
3. See following error:
```
{ Error: Number can only safely store up to 53 bits    at PromiEvent (/home/billy/GitHub.com/clovers-network/clovers-contracts/node_modules/@nomiclabs/truffle-contract/lib/promievent.js:14:30)
    at /home/billy/GitHub.com/clovers-network/clovers-contracts/node_modules/@nomiclabs/truffle-contract/lib/execute.js:218:26
    at Function.new (/home/billy/GitHub.com/clovers-network/clovers-contracts/node_modules/@nomiclabs/truffle-contract/lib/contract/constructorMethods.js:33:59)
    at deployAllContracts (/home/billy/GitHub.com/clovers-network/clovers-contracts/helpers/deployAllContracts.js:81:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  hijackedStack:
   'Error: Number can only safely store up to 53 bits\n    at assert (/home/billy/GitHub.com/clovers-network/clovers-contracts/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6:21)\n    at BN.toNumber (/home/billy/GitHub.com/clovers-network/clovers-contracts/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:506:7)\n    at Object.hexToNumber (/home/billy/GitHub.com/clovers-network/clovers-contracts/node_modules/web3-utils/src/utils.js:234:24)\n    at Method.outputBlockFormatter (/home/billy/GitHub.com/clovers-network/clovers-contracts/node_modules/web3-core-helpers/src/formatters.js:237:28)\n    at Method.web3.eth.getBlock.method.outputFormatter.block [as outputFormatter] (/home/billy/GitHub.com/clovers-network/clovers-contracts/node_modules/@truffle/interface-adapter/lib/ethereum-overloads.ts:25:32)\n    at Method.formatOutput (/home/billy/GitHub.com/clovers-network/clovers-contracts/node_modules/web3-core-method/src/index.js:164:54)\n    at sendTxCallback (/home/billy/GitHub.com/clovers-network/clovers-contracts/node_modules/web3-core-method/src/index.js:474:33)\n    at /home/billy/GitHub.com/clovers-network/clovers-contracts/node_modules/web3-core-requestmanager/src/index.js:147:9\n    at cb (util.js:353:39)\n    at process._tickCallback (internal/process/next_tick.js:63:19)' }
```

__Expected behavior:__ No error

__Actual behavior:__ Error occured

__Additional info:__ Tracing this bug back to `web3-core-helpers/src/formatters.js:237:28` shows that the receipt from the transaction of a deployed contract resulted in the parameter `gasLimit` was equal to `0xffffffffffffffff`. This value was apparently too large for big number to process using the library `web3-utils` method `hexToNumber()`

**Comment by okwme** [comment]
Actually this is coming from `eth_getBlockByHash`. For example I deploy a contract in one block and truffle is trying to check the success (i think that's why) it calls the block by hash:
```json
{"jsonrpc":"2.0","method":"eth_getBlockByHash","params":["0x40081510b9d8b2d0f592faa7ebdce0b79dcf5e354612042db882c300557c01fd", true],"id":1}
```
The results are as follows:
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "difficulty": null,
    "extraData": null,
    "gasLimit": "0xffffffffffffffff",
    "gasUsed": "0x0",
    "hash": "0x40081510b9d8b2d0f592faa7ebdce0b79dcf5e354612042db882c300557c01fd",
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "miner": "0xec48c26c6fecdeefc6467656a4409452e25f706fed52ba26b034838ba3f7cae4",
    "nonce": null,
    "number": "0x8d7",
    "parentHash": "0x80aafa116e683b750480596b1b7389a96a95fb77ae42872ea3560f52a282a531",
    "sha3Uncles": null,
    "size": "0x22b",
    "stateRoot": "0xa34a8f30b319c26400cb56ead63be5ab20c317510e08c4d6ac38d25012d215ac",
    "timestamp": "0x5dc1f5c4",
    "totalDifficulty": null,
    "transactions": [],
    "transactionsRoot": "0x",
    "uncles": null
  }
}
```
The value inside of `gasLimit` breaks bigNumber.

The value inside of `miner` does not checksum correctly

**Comment by austinabell** [comment]
Ah yes, Tendermint's default block gas limit is -1, which indicates there is no block gas limit, which got formatted to 0xfff.. when using geth's formatting utils. Thanks for this find, I will see what options there are for returning a value for this to ensure compatibility with dev tooling
