### ISSUE TITLE
web3.eth.getblock error "failed to get block bloom mapping"

### ISSUE THREAD

**Issue by letterj** [cosmos/ethermint#242]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]
Commit: 35e7a98ab2947f7a95c1bacb9262d252347c918b
MacOS

__Steps to reproduce:__

1. deploy ethermint chain 
2. run `npm run testDeploy` from github.com/chainsafe/ethermint-scripts

__Expected behavior:__ 
```
curl -X POST \
   --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x5b", true],"id":1}' \
   -H "Content-Type: application/json" \
   http://localhost:8545

{"jsonrpc":"2.0","id":1,"result":{"difficulty":null,"extraData":null,"gasLimit":"0xffffffff","gasUsed":"0x47b760","hash":"0x496021a74bad57f9ff8dba2481817c08d6d253846e40127023f2bd94d51b5a39","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000020002000000000000000000000000000000000000000000000000000000000000000200000000000000000000000001000008000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000400000080000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000100000000800000000000000000000000000000000","miner":"0x0000000000000000000000000000000000000000","nonce":null,"number":"0x5b","parentHash":"0x9530919961404a4b8ea5be71eacf7726322ead4ac0ebac810c37c654c052e374","sha3Uncles":null,"size":"0x369","stateRoot":"0xa8486d186e1dc1439070664b40805fd8e271c24700492b0785eba2859f5b1c30","timestamp":"0x5e87b49d","totalDifficulty":null,"transactions":[{"blockHash":"0x496021a74bad57f9ff8dba2481817c08d6d253846e40127023f2bd94d51b5a39","blockNumber":"0x5b","from":"0xb990eefd1c6c2168609c561b526697ac34339cbd","gas":"0x72bf0","gasPrice":"0xa","hash":"0xb937a45f150b7e54f8bb3a42d9e853724f5016e4b8c81c9c0512f10d3260b78a","input":"0x221564090000000000000000000000000000000000000000000000000000000000000000","nonce":"0xc","to":"0xcdb226dc2f37a8c3938ae7adc371450981932ca8","transactionIndex":"0x0","value":"0x0","v":"0x34","r":"0x413f7ab557d98eff4b65fc82759539464432e8f0648922c73a33a27f69a2145c","s":"0x778168465541f1344b2f7d10b240bfe90527e0eb345916191e539975409af07c"}],"transactionsRoot":"0x95f343aac0dc7b107294a9dcf326014fa100ee8b27c8ebb77c6c4af6fc16c546","uncles":null}}
```

__Actual behavior:__ [What actually happened]

```
 block number: 91
(node:74627) UnhandledPromiseRejectionWarning: Error: Returned error: {"codespace":"sdk","code":1,"message":"failed to get block bloom mapping: block with bloombits [] not found"}
    at Object.ErrorResponse (/Users/letterj/workshop/chainsafe/ethermint-scripts/web3/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/letterj/workshop/chainsafe/ethermint-scripts/web3/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/Users/letterj/workshop/chainsafe/ethermint-scripts/web3/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/letterj/workshop/chainsafe/ethermint-scripts/web3/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/letterj/workshop/chainsafe/ethermint-scripts/web3/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/Users/letterj/workshop/chainsafe/ethermint-scripts/web3/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/Users/letterj/workshop/chainsafe/ethermint-scripts/web3/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:74627) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:74627) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

__Additional info:__ [Include gist of relevant config, logs, etc.]
All unit tests pass

**Comment by noot** [comment]
this is the source of the issue: https://github.com/ChainSafe/ethermint/blob/eaaae0e3fd0f4631184257160563a233271c1516/x/evm/keeper/keeper.go#L99

the bloom is probably not being set properly.
