### ISSUE TITLE
Fix Ethermint-Deploy contract

### ISSUE THREAD

**Issue by fedekunze** [cosmos/ethermint#391]
https://github.com/ChainSafe/ethermint-deploy setup is failing 

```
yarn start                                  
yarn run v1.15.2
$ node ./web3/deploy_contract.js
Compiling contract code...
Unlocked account address: 	 0x6814A3A2180AF58816f9D7f9A0383D52c4cCBb51
Deploying contract...
Deployed contract Address: 	 0x11bCB8673b57DE199F71E159d9e1587eb0D1A8AD
Error: Returned error: method handler crashed
    at Object.ErrorResponse (/Users/federico/ethermint-deploy/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/federico/ethermint-deploy/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/Users/federico/ethermint-deploy/node_modules/web3-providers-http/src/index.js:102:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/federico/ethermint-deploy/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/federico/ethermint-deploy/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/Users/federico/ethermint-deploy/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/Users/federico/ethermint-deploy/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Counter pre increment is: 	 undefined
Sending add transaction...
Add tx finalized in block: 	 4
Error: Returned error: method handler crashed
    at Object.ErrorResponse (/Users/federico/ethermint-deploy/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/federico/ethermint-deploy/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/Users/federico/ethermint-deploy/node_modules/web3-providers-http/src/index.js:102:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/federico/ethermint-deploy/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/federico/ethermint-deploy/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/Users/federico/ethermint-deploy/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/Users/federico/ethermint-deploy/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Counter post increment is: 	 undefined
✨  Done in 11.87s.
```

**Comment by fedekunze** [comment]
doesn't apply anymore as we have CI tests now
