### ISSUE TITLE
panic "wrong Block.Header.AppHash" happened when restart a node with snapshot

### ISSUE THREAD

**Issue by KamiD** [cosmos/ethermint#672]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__
Reproduce every time

1. [First Step]
* Deploy 4 node with ethermintd

2. [Second Step]
* Publish some contract and call it on ethermint

3. [and so on...]
* Restart one of nodes

__Expected behavior:__ [What you expected to happen]
Node runs well

__Actual behavior:__ [What actually happened]
Panic happened, following code is error logs:
```shell
panic: Failed to process committed block (343:9150EFAEF4EBF5D9FF30BC07677883BBB69CC2FAE0AFB4FA38E27B6A2CE3C983): wrong Block.Header.AppHash.  Expected B54B85040B67913D1591D3AB62BE9F439852C67FD6C237BCACC3CA247B10C977, got AB17E63A9276B773384161A5A06A63897DC3985F30CF1EA7BF19309720CFF20C

goroutine 165 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0001876c0)
        /Users/oker/work/go/pkg/mod/github.com/okex/tendermint@v0.33.9-okexchain1/blockchain/v0/reactor.go:349 +0x12ed
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /Users/oker/work/go/pkg/mod/github.com/okex/tendermint@v0.33.9-okexchain1/blockchain/v0/reactor.go:118 +0x84

```

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by KamiD** [comment]
A simple analyzes:
https://github.com/cosmos/ethermint/blob/9659b81ee1bf27f979b5f0793778ff97e2fc62b6/x/evm/keeper/abci.go#L32
https://github.com/cosmos/ethermint/blob/9659b81ee1bf27f979b5f0793778ff97e2fc62b6/x/evm/keeper/abci.go#L33
You should not change `keeper.Bloom` and `keeper.TxCount`  during calling function of BeginBlock, Cause that AppModule was a struct(not a pointer), when the function `AppModule.BeginBlock` has called, The actually value in keeper will not changed by `=`
