### ISSUE TITLE
Faild to add a multisig key by the --multisig flag

### ISSUE THREAD

**Issue by ylsGit** [cosmos/ethermint#716]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

* branch development

__Steps to reproduce:__

1. [First Step]
```
ethermintcli keys add signer-1
ethermintcli keys add signer-2
ethermintcli keys add signer-3
```
2. [Second Step]
```
ethermintcli keys add wallet-ms --multisig signer-1,signer-2,signer-3 --multisig-threshold 2
```

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

```
panic: Cannot encode unregistered concrete type ethsecp256k1.PubKey.

goroutine 1 [running]:
github.com/tendermint/go-amino.(*Codec).MustMarshalBinaryBare(...)
	/Users/oker/go/pkg/mod/github.com/tendermint/go-amino@v0.15.1/amino.go:225
github.com/tendermint/tendermint/crypto/multisig.PubKeyMultisigThreshold.Bytes(0x2, 0xc0011922c0, 0x3, 0x4, 0x3c0, 0x1f8, 0x3f)
	/Users/oker/go/pkg/mod/github.com/tendermint/tendermint@v0.33.9/crypto/multisig/threshold_pubkey.go:72 +0xee
github.com/tendermint/tendermint/crypto/multisig.PubKeyMultisigThreshold.Address(0x2, 0xc0011922c0, 0x3, 0x4, 0xc00017ac00, 0xc00001b200, 0xc000321500)
	/Users/oker/go/pkg/mod/github.com/tendermint/tendermint@v0.33.9/crypto/multisig/threshold_pubkey.go:77 +0x50
github.com/cosmos/cosmos-sdk/crypto/keys.multiInfo.GetAddress(...)
	/Users/oker/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.2/crypto/keys/types.go:325
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.writeInfo(0x50f6950, 0x50f6948, 0x5983060, 0x2, 0x2, 0x5983060, 0x2, 0x2, 0x523ffe0, 0xc000326270, ...)
	/Users/oker/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.2/crypto/keys/keyring.go:482 +0x250
github.com/cosmos/cosmos-sdk/crypto/keys.baseKeybase.writeMultisigKey(0x50f6950, 0x50f6948, 0x5983060, 0x2, 0x2, 0x5983060, 0x2, 0x2, 0x521e500, 0xc000d3a870, ...)
	/Users/oker/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.2/crypto/keys/keybase_base.go:247 +0xab
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.CreateMulti(...)
	/Users/oker/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.2/crypto/keys/keyring.go:127
github.com/cosmos/cosmos-sdk/client/keys.RunAddCmd(0xc00145a000, 0xc0005ab1d0, 0x1, 0x5, 0x5250380, 0xc000d3a0a0, 0xc001030180, 0xc0011b7c40, 0x41dcfa5)
	/Users/oker/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.2/client/keys/add.go:165 +0xff1
github.com/cosmos/ethermint/client.runAddCmd(0xc00145a000, 0xc0005ab1d0, 0x1, 0x5, 0x0, 0x0)
	/Users/oker/go/src/github.com/cosmos/ethermint/client/keys.go:71 +0x16a
github.com/spf13/cobra.(*Command).execute(0xc00145a000, 0xc0005ab180, 0x5, 0x5, 0xc00145a000, 0xc0005ab180)
	/Users/oker/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005a62c0, 0x450b605, 0xc0005a62c0, 0x4ecd691)
	/Users/oker/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/oker/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0005a62c0, 0x50f9888, 0x2, 0xc001026f00)
	/Users/oker/go/pkg/mod/github.com/tendermint/tendermint@v0.33.9/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/oker/go/src/github.com/cosmos/ethermint/cmd/ethermintcli/main.go:82 +0x40b
```
__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by fedekunze** [comment]
multisigs are not supported for keys other than `secp256k1` for the moment
