### ISSUE TITLE
enterPrevote: ProposalBlock is invalid

### ISSUE THREAD

**Issue by harvey2953** [cosmos/ethermint#924]
__System info:__ 
name: ethermint
server_name: ethermintd
client_name: ethermintcli
version: 0.4.1-10-g3596d53
commit: 3596d535e1e32113604c122ffbdb0c68fac35ba3
build_tags: netgo,ledger
go: go version go1.16.3 darwin/amd64

__Steps to reproduce:__

1. make localnet-start
2. remix deploy contract to node0
3. tail -f emintd.log

__Expected behavior:__ 
```bash
I[2021-08-09|13:35:33.050] Executed block                               module=state height=44867 validTxs=0 invalidTxs=0
I[2021-08-09|13:35:33.075] Committed state                              module=state height=44867 txs=0 appHash=DC50913D13E9AB5B5C4F501C6E883C6A6A882CED329ABCBBB7C4284AC22CBE82
```
__Actual behavior:__ 
node0
```bash
I[2021-08-09|13:35:42.841] Added good transaction                       module=mempool tx=C183497BE36146D447FFC00F8EAD46882C2F701F7CFE3C0259562F77ACC70035 res="&{CheckTx:log:\"[]\" gas_wanted:3521879 }" height=44868 total=1
E[2021-08-09|13:35:43.502] enterPrevote: ProposalBlock is invalid       module=consensus height=44869 round=0 err="wrong Block.Header.AppHash.  Expected 2817DE07DAAE06E6F52B4562439CEF7DB9739BFA00DC1D26161BA36E0F467C04, got DA312E73F6D64EC8CCFAE34FA20D2C123B94DB3D837543934AC87F17A916A7B1"
E[2021-08-09|13:35:43.503] CONSENSUS FAILURE!!!                         module=consensus err="enterPrecommit: +2/3 prevoted for an invalid block: wrong Block.Header.AppHash.  Expected 2817DE07DAAE06E6F52B4562439CEF7DB9739BFA00DC1D26161BA36E0F467C04, got DA312E73F6D64EC8CCFAE34FA20D2C123B94DB3D837543934AC87F17A916A7B1" stack="goroutine 944576 [running]:\nruntime/debug.Stack(0xc0006ab380, 0x4e9c760, 0xc004751bb0)\n\t/usr/local/Cellar/go/1.16.3/libexec/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2(0xc001291500, 0x5258b10)\n\t/Users/XXX/Workspace/Environment/GoPath/pkg/mod/github.com/tendermint/tendermint@v0.33.9/consensus/state.go:629 +0x5b\npanic(0x4e9c760, 0xc004751bb0)\n\t/usr/local/Cellar/go/1.16.3/libexec/src/runtime/panic.go:965 +0x1b9\ngithub.com/tendermint/tendermint/consensus.(*State).enterPrecommit(0xc001291500, 0xaf45, 0x0)\n\t/Users/XXX/Workspace/Environment/GoPath/pkg/mod/github.com/tendermint/tendermint@v0.33.9/consensus/state.go:1245 +0x1646\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc001291500, 0xc0072612c0, 0xc001012030, 0x28, 0xc0006abbf0, 0x4a098c7, 0xc008a06210)\n\t/Users/XXX/Workspace/Environment/GoPath/pkg/mod/github.com/tendermint/tendermint@v0.33.9/consensus/state.go:1887 +0x1008\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc001291500, 0xc0072612c0, 0xc001012030, 0x28, 0x4f6bbc0, 0xed8a2b501, 0xc003c41fb0)\n\t/Users/XXX/Workspace/Environment/GoPath/pkg/mod/github.com/tendermint/tendermint@v0.33.9/consensus/state.go:1725 +0x59\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc001291500, 0x53ca3e0, 0xc003e50eb0, 0xc001012030, 0x28)\n\t/Users/XXX/Workspace/Environment/GoPath/pkg/mod/github.com/tendermint/tendermint@v0.33.9/consensus/state.go:725 +0x545\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc001291500, 0x0)\n\t/Users/XXX/Workspace/Environment/GoPath/pkg/mod/github.com/tendermint/tendermint@v0.33.9/consensus/state.go:660 +0x3c5\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\t/Users/XXX/Workspace/Environment/GoPath/pkg/mod/github.com/tendermint/tendermint@v0.33.9/consensus/state.go:347 +0x168\n"
```

other node:
```bash
err="tx already exists in cache\ngithub.com/tendermint/tendermint/mempool.init\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.33.9/mempool/errors.go:11\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5652\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5647\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5647\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5647\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5647\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5647\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:191\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"
```

__Contract:__ 
```solidity
pragma solidity ^0.5.11;

contract Counter {
  uint256 counter = 0;

  function add() public {
    counter++;
  }

  function subtract() public {
    counter--;
  }

  function getCounter() public view returns (uint256) {
    return counter;
  }
}
```

**Comment by fedekunze** [comment]
Hey @ikerlin, ongoing development has been migrated to https://github.com/tharsis/ethermint

**Comment by harvey2953** [comment]
> Hey @ikerlin, ongoing development has been migrated to https://github.com/tharsis/ethermint

This repository will be archived?
